# Generated by Django 3.2.5 on 2021-07-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('authors', models.TextField()),
                ('published_date', models.DateField()),
                ('ISBN_10', models.BigIntegerField()),
                ('ISBN_13', models.BigIntegerField()),
                ('page_count', models.IntegerField()),
                ('front_cover_link', models.URLField()),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
