# Generated by Django 3.2.5 on 2021-07-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN_10',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN_13',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='front_cover_link',
            field=models.URLField(default='https://images-na.ssl-images-amazon.com/images/I/21u5Kw1n+IL._SX331_BO1,204,203,200_.jpg'),
        ),
    ]
