# Generated by Django 3.2.5 on 2021-07-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='front_cover_link',
            field=models.URLField(),
        ),
    ]
