# Generated by Django 3.2.5 on 2021-07-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_book_front_cover_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN_10',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN_13',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
